export const HOME_SCREEN = 'lxm.HomeScreen'
export const PLAY_DETAIL_SCREEN = 'lxm.PlayDetailScreen'
export const SONGLIST_DETAIL_SCREEN = 'lxm.SonglistDetailScreen'
export const COMMENT_SCREEN = 'lxm.CommentScreen'
export const SOURCE_MANAGER_SCREEN = 'lxm.SourceManagerScreen'
export const SETTING_SCREEN = 'lxm.SettingScreen'
export const VERSION_MODAL = 'lxm.VersionModal'
export const PACT_MODAL = 'lxm.PactModal'
export const SYNC_MODE_MODAL = 'lxm.SyncModeModal'

